# Generated by Django 3.0.8 on 2020-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AS_OF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_modified', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Date Modified',
            },
        ),
        migrations.CreateModel(
            name='THC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('probationary', models.IntegerField(default=0)),
                ('regular', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('married', models.IntegerField(default=0)),
                ('single', models.IntegerField(default=0)),
                ('g1', models.IntegerField(default=0)),
                ('g2', models.IntegerField(default=0)),
                ('g3', models.IntegerField(default=0)),
                ('g4', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'THC',
            },
        ),
        migrations.CreateModel(
            name='TTECH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('probationary', models.IntegerField(default=0)),
                ('regular', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('married', models.IntegerField(default=0)),
                ('single', models.IntegerField(default=0)),
                ('g1', models.IntegerField(default=0)),
                ('g2', models.IntegerField(default=0)),
                ('g3', models.IntegerField(default=0)),
                ('g4', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'T-TECH',
            },
        ),
        migrations.CreateModel(
            name='YTMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_a', models.IntegerField(default=0)),
                ('khmpc_a', models.IntegerField(default=0)),
                ('reg_b', models.IntegerField(default=0)),
                ('khmpc_b', models.IntegerField(default=0)),
                ('reg_rt', models.IntegerField(default=0)),
                ('khmpc_rt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'YTMI Borrowed',
            },
        ),
    ]
