# Generated by Django 3.0.8 on 2020-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'PRESENT'), ('L', 'LATE'), ('A', 'ABSENT')], max_length=5),
        ),
    ]
