# Generated by Django 3.0.8 on 2020-08-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20200804_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
