# Generated by Django 3.0.8 on 2020-08-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_april_august_december_february_january_july_june_march_may_november_october_september'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'EMPLOYEES'},
        ),
    ]
