# Generated by Django 3.0.8 on 2020-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20200806_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='april',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='april',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='august',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='december',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='february',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='january',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='july',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='june',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='march',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='november',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d31',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='october',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d1',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d10',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d11',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d12',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d13',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d14',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d15',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d16',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d17',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d18',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d19',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d2',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d20',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d21',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d22',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d23',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d24',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d25',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d26',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d27',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d28',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d29',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d3',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d30',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d4',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d5',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d6',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d7',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d8',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='september',
            name='d9',
            field=models.CharField(blank=True, default='NULL', max_length=5, null=True),
        ),
    ]
