# Generated by Django 3.0.8 on 2020-08-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20200806_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='april',
            options={'verbose_name': 'APRIL', 'verbose_name_plural': 'APRIL'},
        ),
        migrations.AlterModelOptions(
            name='august',
            options={'verbose_name': 'AUGUST', 'verbose_name_plural': 'AUGUST'},
        ),
        migrations.AlterModelOptions(
            name='december',
            options={'verbose_name': 'DECEMBER', 'verbose_name_plural': 'DECEMBER'},
        ),
        migrations.AlterModelOptions(
            name='february',
            options={'verbose_name': 'FEBRUARY', 'verbose_name_plural': 'FEBRUARY'},
        ),
        migrations.AlterModelOptions(
            name='january',
            options={'verbose_name': 'JANUARY', 'verbose_name_plural': 'JANUARY'},
        ),
        migrations.AlterModelOptions(
            name='july',
            options={'verbose_name': 'JULY', 'verbose_name_plural': 'JULY'},
        ),
        migrations.AlterModelOptions(
            name='june',
            options={'verbose_name': 'JUNE', 'verbose_name_plural': 'JUNE'},
        ),
        migrations.AlterModelOptions(
            name='march',
            options={'verbose_name': 'MARCH', 'verbose_name_plural': 'MARCH'},
        ),
        migrations.AlterModelOptions(
            name='may',
            options={'verbose_name': 'MAY', 'verbose_name_plural': 'MAY'},
        ),
        migrations.AlterModelOptions(
            name='november',
            options={'verbose_name': 'NOVEMBER', 'verbose_name_plural': 'NOVEMBER'},
        ),
        migrations.AlterModelOptions(
            name='october',
            options={'verbose_name': 'OCTOBER', 'verbose_name_plural': 'OCTOBER'},
        ),
        migrations.AlterModelOptions(
            name='september',
            options={'verbose_name': 'SEPTEMBER', 'verbose_name_plural': 'SEPTEMBER'},
        ),
    ]
