# Generated by Django 3.0.8 on 2020-08-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfpg',
            options={'verbose_name': 'month', 'verbose_name_plural': 'RFPGS'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'month', 'verbose_name_plural': 'SALES'},
        ),
    ]
