# Generated by Django 3.0.8 on 2020-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creform', '0002_auto_20200804_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
