# Generated by Django 3.0.8 on 2020-08-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='august',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='december',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='february',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='january',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='july',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='june',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='march',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='may',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='november',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='october',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='september',
            name='face_id',
        ),
        migrations.DeleteModel(
            name='april',
        ),
        migrations.DeleteModel(
            name='august',
        ),
        migrations.DeleteModel(
            name='december',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='february',
        ),
        migrations.DeleteModel(
            name='january',
        ),
        migrations.DeleteModel(
            name='july',
        ),
        migrations.DeleteModel(
            name='june',
        ),
        migrations.DeleteModel(
            name='march',
        ),
        migrations.DeleteModel(
            name='may',
        ),
        migrations.DeleteModel(
            name='november',
        ),
        migrations.DeleteModel(
            name='october',
        ),
        migrations.DeleteModel(
            name='september',
        ),
    ]
