# Generated by Django 3.0.8 on 2020-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_april_august_december_employee_february_january_july_june_march_may_november_october_september'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
