# Generated by Django 3.0.8 on 2020-08-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_auto_20200812_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='logbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.CharField(choices=[('I', 'IN'), ('O', 'OUT')], max_length=1)),
                ('employee', models.ForeignKey(db_column='face_id', on_delete=django.db.models.deletion.CASCADE, to='contractor.employee', to_field='face_id')),
            ],
            options={
                'verbose_name_plural': 'LOGBOX',
            },
        ),
    ]
