# Generated by Django 3.0.8 on 2020-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0006_auto_20200817_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_id',
            field=models.IntegerField(unique=True),
        ),
    ]
