# Generated by Django 3.0.8 on 2020-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0007_auto_20200817_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': 'AUGUST 16, 2020 - AUGUST 22, 2020'},
        ),
        migrations.AlterModelOptions(
            name='lasweek',
            options={'verbose_name_plural': 'AUGUST 09, 2020 - AUGUST 15, 2020'},
        ),
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
