# Generated by Django 3.0.8 on 2020-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0008_auto_20200818_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbox',
            name='shift',
            field=models.CharField(choices=[('DS', 'DAY SHIFT'), ('NS', 'NIGHT SHIFT')], default='DS', max_length=2),
        ),
    ]
