# Generated by Django 3.0.8 on 2020-08-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0009_logbox_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurWeekNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'AUGUST 16, 2020 - AUGUST 22, 2020NIGHT SHIFT',
            },
        ),
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': 'AUGUST 16, 2020 - AUGUST 22, 2020DAY SHIFT'},
        ),
    ]
