# Generated by Django 3.0.8 on 2020-08-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0010_auto_20200818_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': 'AUGUST 16, 2020 - AUGUST 22, 2020 DAY SHIFT'},
        ),
        migrations.AlterModelOptions(
            name='curweekns',
            options={'verbose_name_plural': 'AUGUST 16, 2020 - AUGUST 22, 2020 NIGHT SHIFT'},
        ),
    ]
