# Generated by Django 3.0.8 on 2020-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0013_auto_20200819_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(default='no-avatar.png', upload_to='contractor_pic_files'),
        ),
    ]
