# Generated by Django 3.0.8 on 2020-08-19 15:58

import contractor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0014_auto_20200819_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(default='no-avatar.png', upload_to=contractor.models.content_file_name),
        ),
    ]
