# Generated by Django 3.0.8 on 2020-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0015_auto_20200819_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': 'CURRENT WEEK DS __________(September 06 - September 12)'},
        ),
        migrations.AlterModelOptions(
            name='curweekns',
            options={'verbose_name_plural': 'CURRENT WEEK NS __________(September 06 - September 12)'},
        ),
        migrations.AlterModelOptions(
            name='lasweek',
            options={'verbose_name_plural': 'LAST WEEK DS_______________(August 30 - September 05)'},
        ),
        migrations.AlterModelOptions(
            name='lasweekns',
            options={'verbose_name_plural': 'LAST WEEK NS_______________(August 30 - September 05)'},
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('R', 'REGULAR'), ('NR', 'NON-REGULAR')], default='', max_length=50),
        ),
    ]
