# Generated by Django 3.0.8 on 2020-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0016_auto_20200910_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationTemplateNonRegular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PAYROLL FORM_______________(NON-REGULAR)',
            },
        ),
        migrations.CreateModel(
            name='ComputationTemplateRegular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PAYROLL FORM_______________(REGULAR)',
            },
        ),
    ]
