# Generated by Django 3.1.1 on 2020-09-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0017_computationtemplatenonregular_computationtemplateregular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': 'CURRENT WEEK DS __________(September 20 - September 26)'},
        ),
        migrations.AlterModelOptions(
            name='curweekns',
            options={'verbose_name_plural': 'CURRENT WEEK NS __________(September 20 - September 26)'},
        ),
        migrations.AlterModelOptions(
            name='lasweek',
            options={'verbose_name_plural': 'LAST WEEK DS_______________(September 13 - September 19)'},
        ),
        migrations.AlterModelOptions(
            name='lasweekns',
            options={'verbose_name_plural': 'LAST WEEK NS_______________(September 13 - September 19)'},
        ),
    ]
