# Generated by Django 3.1.1 on 2020-10-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0018_auto_20200923_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': 'CURRENT WEEK DS __________(October 04 - October 10)'},
        ),
        migrations.AlterModelOptions(
            name='curweekns',
            options={'verbose_name_plural': 'CURRENT WEEK NS __________(October 04 - October 10)'},
        ),
        migrations.AlterModelOptions(
            name='lasweek',
            options={'verbose_name_plural': 'LAST WEEK DS_______________(September 27 - October 03)'},
        ),
        migrations.AlterModelOptions(
            name='lasweekns',
            options={'verbose_name_plural': 'LAST WEEK NS_______________(September 27 - October 03)'},
        ),
    ]
